export enum Routes {
  Home = 'Home',
  Feed = 'Feed',
  Login = 'Login',
  SignUp = 'SignUp',
  Projects = 'Projects',
  Profile = 'Profile',
  Splash = 'Splash',
  TopTunes = 'TopTunes',
  Intro = 'Intro',
  Settings = 'Settings',
  Tabs = 'Tabs',
  ProjectDetails = 'ProjectDetails',
  Picture = 'Picture',
}
