name: CI

on:
  push:
    branches:
      - main
      - development
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache-deps.outputs.cache-hit }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: nvmrc
        uses: browniebroke/read-nvmrc-action@v1

      - name: Install Yarn
        run: corepack enable

      - name: Set Yarn version
        run: yarn set version 3.2.3

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies (immutable)
        run: yarn install --immutable
        if: steps.cache-deps.outputs.cache-hit != 'true'

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

      - name: Install Yarn
        run: corepack enable

      - name: Set Yarn version
        run: yarn set version 3.2.3

      - name: Run ESLint
        run: yarn lint
